=== dmgkeke/ssa8-2/com.sds.postjavaprocessor/src/main/resources/PostProcessorConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration" 
	xmlns:tns="http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration" elementFormDefault="qualified">
	
	<element name="postProcessorConfiguration">
		<complexType>
			<all>
				<element name="programming" type="tns:languageType"/>
				<element name="compileConfiguration" type="tns:compileConfiguration"/>
				<element name="createJarConfiguration" type="tns:createJarConfiguration"/>
			</all>
			<!-- <attribute name="폰트" type="폰트타칩" use="required"/> -->
		</complexType>
	</element>
	
	<simpleType name="languageType">
		<restriction base="string">
			<enumeration value="java"/>
		</restriction>
	</simpleType>
	
	<complexType name="compileConfiguration">
		<all>
			<element name="inputFilesPath" type="string" default="./inputfiles"/>
			<element name="outputFilesPath" type="string" default="./inputfiles/classes"/>
		</all>
	</complexType>
	
	<complexType name="createJarConfiguration">
		<all>
			<element name="outputFilePath" type="string" default="./dist"/>
			<element name="fileName" type="string" default="test"/>
		</all>
	</complexType>
	<!-- <simpleType name="암호타입">
		<restriction base="string">
			<pattern value="\d{3}-[A-Z]{2}"/>
		</restriction>
	</simpleType>
	
	<simpleType name="리스트타입">
		<list itemType="integer"/>
	</simpleType>
	
	<simpleType name="폰트타입">
		<union memberTypes="폰트크기, 폰트단위"/>
	</simpleType>
	
	<simpleType name="포트크기">
		<restriction base="integer">
			<maxInclusive value="72"/>
		</restriction>
	</simpleType>
	
	<simpleType name="폰트단위">
		<restriction base="string">
			<enumeration value="small"/>
			<enumeration value="medium"/>
			<enumeration value="large"/>
		</restriction>
	</simpleType> -->
</schema>

=== dmgkeke/ssa8-2/com.sds.postjavaprocessor/config/PostProcessorConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:postProcessorConfiguration 
	xmlns:tns="http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.samsung.com/sds/ssa8-2/PostProcessorConfiguration PostProcessorConfiguration.xsd ">
  
  <tns:programming>java</tns:programming>
  <tns:compileConfiguration>
    <tns:inputFilesPath>./inputfiles</tns:inputFilesPath>
    <tns:outputFilesPath>./outputfiles</tns:outputFilesPath>
  </tns:compileConfiguration>
  <tns:createJarConfiguration>
    <tns:outputFilePath>./output</tns:outputFilePath>
    <tns:fileName>test</tns:fileName>
  </tns:createJarConfiguration>
</tns:postProcessorConfiguration>
